# src/Ens/JobeetBundle/Resources/config/doctrine/CategoryAffiliate.orm.yml
VS\VitrineBundle\Entity\DocFile:
  type: entity
  repositoryClass: VS\VitrineBundle\Repository\DocFileRepository
  table: doc_file
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    file:
      type: string
      length: 255
    path:
      type: string
      length: 255
    size: 
      type: decimal
    mime_type:
      type: string
      length: 255  
    updated_at:
      type: datetime  
  manyToOne:
    storage:
      targetEntity: Storage
      inversedBy: doc_files
      joinColumn:
        name: storage_id
        referencedColumnName: id
  oneToOne:
    storage_unique:
      targetEntity: Link
      inversedBy: doc_file
      joinColumn:
        name: link_id
        referencedColumnName: id