# src/Ens/JobeetBundle/Resources/config/doctrine/CategoryAffiliate.orm.yml
VS\VitrineBundle\Entity\DocFile:
  type: entity
  repositoryClass: VS\VitrineBundle\Repository\DocFileRepository
  table: doc_file
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    file:
      type: string
      length: 255
  manyToOne:
    storage:
      targetEntity: Storage
      inversedBy: doc_files
      joinColumn:
        name: storage_id
        referencedColumnName: id