article:
    pattern:  /{page}
    defaults: { _controller: "VSVitrineBundle:Article:index", page: 1 }
    requirements: 
      page: \d+

article_show:
    pattern:  /{id}/show
    defaults: { _controller: "VSVitrineBundle:Article:show" }
