<?php

namespace VS\VitrineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
	public function getArticlesQuery()
	{
		$q = $this->createQueryBuilder("a")
					->orderBy('a.created_at', 'DESC');
		return $q;
	}
	
	public function getLatestArticles($max = null){
		$qb = $this->createQueryBuilder("a")
				->orderBy("a.created_at", "DESC");
		if($max){
			$qb->setMaxResults($max);
		}
		$query = $qb->getQuery();
		return $query->getResult(); 
	}
}
