<?php

namespace VS\VitrineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarouselSlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarouselSlotRepository extends EntityRepository
{
	public function getActiveCarouselSlots(){
		$qb = $this->createQueryBuilder("c")
			->where("c.activated = :activated")->setParameter("activated", 1);
		$query = $qb->getQuery();
		return $query->getResult();
	}
}
