<?php

namespace VS\VitrineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
	public function getCurrentEventsQuery(){
		$q = $this->createQueryBuilder("e")
			->where("e.event_date > :date")->setParameter("date", date("Y-m-d H:i:s", time()))
			->orderBy("e.event_date", "ASC")
			;
		return $q;
	}
	
	public function getLastEvent()	{
		$q = $this->getCurrentEventsQuery()
			->getQuery()
			->setMaxResults(1);
		
		return $q->getOneOrNullResult();
	}
	
	public function getCurrentEventsOrdered(){
		$q = $this->getCurrentEventsQuery();
		$events = $q->getQuery()->getResult();
		
		if(!isset($events[0])){
			return null;
		}
		$month = $events[0]->getEventDate()->format("m");
		$i = 0;
		
		foreach($events as $event)	{
			if($event->getEventDate()->format("m") != $month){
				$i++;	
				$month = $event->getEventDate()->format("m");
			}
			$sortedEvents[$i][] = $event;
		}
		unset($events);
		
		return $sortedEvents;
	}
}
