<?php

namespace VS\VitrineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StorageUniqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StorageUniqueRepository extends EntityRepository
{
}
