<?php

namespace VS\VitrineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SurveyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SurveyRepository extends EntityRepository
{
	public function getLastSurvey(){
		$q = $this->createQueryBuilder("s");
		
			$q->select("s", "a")
				->orderBy("s.created_at", "DESC")
				->join("s.survey_answers", "a")
				//->setMaxResults(1)
			;
		return $q->getQuery()->getOneOrNullResult();
	}
	
}
